//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectionMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectedNode
    {
        public int CurrentNode { get; set; }
        public int ConnectedTo { get; set; }
        public int RecordID { get; set; }
    
        public virtual StreetNode StreetNode { get; set; }
        public virtual StreetNode StreetNode1 { get; set; }
    }
}
