//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectionMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentID { get; set; }
        public double DepartmentX { get; set; }
        public double DepartmentY { get; set; }
        public string DepartmentName { get; set; }
    }
}
