//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectionMap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MapDBEntities : DbContext
    {
        public MapDBEntities()
            : base("name=MapDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConnectedNode> ConnectedNodes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<StreetNode> StreetNodes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
