//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectionMap
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreetNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StreetNode()
        {
            this.ConnectedNodes = new HashSet<ConnectedNode>();
            this.ConnectedNodes1 = new HashSet<ConnectedNode>();
        }
    
        public double StreetNodeX { get; set; }
        public double StreetNodeY { get; set; }
        public int StreetNodeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectedNode> ConnectedNodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConnectedNode> ConnectedNodes1 { get; set; }
    }
}
